version: '3.3'

services:
  app:
    image: hello-world-php:latest
    build:
      context: .
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
      - POSTGRES_HOST=pg
    volumes:
      - .:/usr/src/hello_world

  pg:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
    volumes:
      - ./sql/create_requests_table.sql:/docker-entrypoint-initdb.d/create_requests_table.sql

  client:
    image: jfahrer/checker-u-dev-a3:latest
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
      - POSTGRES_HOST=pg

  lb:
    image: jfahrer/lb:latest
    environment:
      - PROXY_UPSTREAM=app:80
    ports:
      - 8000:80